-- Active: 1745889708778@@127.0.0.1@3306@community



-- DROP DATABASE IF EXISTS `community`;
-- CREATE DATABASE `community`
--     DEFAULT CHARACTER SET = 'utf8mb4';






DROP TABLE IF EXISTS `posts`;

CREATE TABLE `posts` (
	`no`	BIGINT	NOT NULL	COMMENT '번호',
	`id`	VARCHAR(64)	NOT NULL	COMMENT 'UK',
	`user_no`	BIGINT	NOT NULL	COMMENT '회원번호',
	`title`	VARCHAR(100)	NOT NULL	COMMENT '제목',
	`content`	TEXT	NULL	COMMENT '내용',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
	`no`	BIGINT	NOT NULL	COMMENT 'PK',
	`id`	VARCHAR(64)	NOT NULL	COMMENT 'UK',
	`uesername`	VARCHAR(100)	NOT NULL	COMMENT '아이디',
	`password`	VARCHAR(100)	NOT NULL	COMMENT '비밀번호',
	`name`	VARCHAR(50)	NOT NULL	COMMENT '이름',
	`email`	VARCHAR(200)	NOT NULL	COMMENT '이메일',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자'
);

DROP TABLE IF EXISTS `COMMENTS`;

CREATE TABLE `COMMENTS` (
	`no`	BIGINT	NOT NULL	COMMENT 'PK',
	`id`	VARCHAR(64)	NOT NULL	COMMENT 'UK',
	`post_no`	BIGINT	NOT NULL	COMMENT '게시글번호',
	`user_no`	BIGINT	NOT NULL	COMMENT '회원번호',
	`content`	VARCHAR(64)	NOT NULL	COMMENT '내용',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자'
);

DROP TABLE IF EXISTS `File`;

CREATE TABLE `File` (
	`no`	BIGINT	NOT NULL	COMMENT 'PK',
	`id`	VARCHAR(64)	NOT NULL	COMMENT 'UK',
	`post_no`	BIGINT	NOT NULL	COMMENT '게시글 번호',
	`file_name`	VARCHAR(100)	NOT NULL	COMMENT '파일명',
	`file_path`	VARCHAR(255)	NOT NULL,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자'
);

ALTER TABLE `posts` ADD CONSTRAINT `PK_POSTS` PRIMARY KEY (
	`no`
);

ALTER TABLE `users` ADD CONSTRAINT `PK_USERS` PRIMARY KEY (
	`no`
);

ALTER TABLE `COMMENTS` ADD CONSTRAINT `PK_COMMENTS` PRIMARY KEY (
	`no`
);

ALTER TABLE `File` ADD CONSTRAINT `PK_FILE` PRIMARY KEY (
	`no`
);

ALTER TABLE `posts` ADD CONSTRAINT `FK_users_TO_posts_1` FOREIGN KEY (
	`user_no`
)
REFERENCES `users` (
	`no`
);

ALTER TABLE `COMMENTS` ADD CONSTRAINT `FK_posts_TO_COMMENTS_1` FOREIGN KEY (
	`post_no`
)
REFERENCES `posts` (
	`no`
);

ALTER TABLE `COMMENTS` ADD CONSTRAINT `FK_users_TO_COMMENTS_1` FOREIGN KEY (
	`user_no`
)
REFERENCES `users` (
	`no`
);

ALTER TABLE `File` ADD CONSTRAINT `FK_posts_TO_File_1` FOREIGN KEY (
	`post_no`
)
REFERENCES `posts` (
	`no`
);



